### ISSUE TITLE
Can I run it on windows 7 installation?

### ISSUE THREAD

**Issue by jsteerv** [JulienBernard/starter-laravel-angular-foundation#1]
I am trying to, but i cant complete the installation steps:
- npm install
- gulp && gulp watch

And when i run the app it shows: 

ErrorException in helpers.php line 668:
file_get_contents(C:\wamp\www\starter-laravel-angular-foundation-master\public/build/rev-manifest.json): failed to open stream: No such file or directory (View: C:\wamp\www\starter-laravel-angular-foundation-master\resources\views\layout.blade.php)

ErrorException in helpers.php line 668:
file_get_contents(C:\wamp\www\starter-laravel-angular-foundation-master\public/build/rev-manifest.json): failed to open stream: No such file or directory

**Comment by JulienBernard** [comment]
Hi,

Did you install all the requirements? Did you ran `composer install --prefer-dist`?
I updated the [README file](https://github.com/JulienBernard/starter-laravel-angular-foundation/blob/master/README.md), it is more comprehensive now.

Tell me if it's ok now :)
