### ISSUE TITLE
Missing and out of place files.

### ISSUE THREAD

**Issue by necrogami** [JulienBernard/starter-laravel-angular-foundation#2]
Missing, .env.example

/resources/{js,css} should be /resources/assets/{js,css}

in node_modules/laravel-elixir/Config.js you need to disable babel in order for the compiliation to properly work.

**Comment by necrogami** [comment]
Once all that is corrected things work out of the box.

Until you complete those steps things won't work.

**Comment by JulienBernard** [comment]
Hi Necrogami,

When I have some free time, I'll take a look on this, thanks for the feedback.
If you are more advices, please feel free to make a pull request directly ;)
